import { execFile } from 'node:child_process'
import { createHash } from 'node:crypto'
import { z } from 'zod'
import type { CommandContext, Provider } from './types.js'
import { tr } from '../i18n.js'

/**
 * The clipboard history.
 *
 * Everything here lives in memory and only in memory: nothing is written to `data/`, nothing is
 * logged, and nothing leaves the Mac. The pasteboard is read only while a widget is subscribed to
 * the channel — the registry starts and stops the polling with the last subscriber — and an entry
 * that looks like a secret is kept copyable but never shown.
 */

/** How many distinct entries are remembered. */
export const MAX_ENTRIES = 20
/** Largest text kept per entry. Anything longer is truncated before it is stored. */
export const MAX_TEXT_BYTES = 2048
/** How much of an entry the widget is shown. */
export const PREVIEW_CHARS = 120
/** What stands in for the preview of an entry that looks like a secret. */
export const MASKED_PREVIEW = '••••'
/** A run of this many characters with no whitespace reads as a token, not as prose. */
export const SECRET_MIN_LENGTH = 32
/**
 * A shorter unbroken run still reads as a credential when it mixes character classes.
 *
 * An ordinary password is eight to twenty characters with letters, digits and punctuation in it —
 * well under the 32 above, which only ever caught API keys. Eight is where a password stops
 * looking like a word.
 */
export const SECRET_TOKEN_MIN_LENGTH = 8

/** Substrings that mark a text as a secret whatever its shape. Matched case-insensitively. */
const SECRET_MARKERS = ['password', 'mot de passe', 'secret', 'bearer', 'private key', 'sk-', 'ghp_', 'github_pat_', 'xoxb-', 'api key', 'apikey']

/**
 * Pasteboard types that say "do not keep this".
 *
 * A password manager marks what it copies as concealed, and a few applications mark a transient
 * value the same way. `pbpaste` reports neither — it hands over the text and says nothing — so
 * the types have to be read separately. Honoured by not recording the entry at all.
 *
 * https://github.com/sindresorhus/Pasteboard-Viewer documents the convention.
 */
export const PRIVATE_PASTEBOARD_TYPES = [
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.TransientType',
  'org.nspasteboard.AutoGeneratedType',
]

/**
 * How many of lower, upper, digit and symbol a text draws on.
 *
 * Unicode-aware on purpose: `[a-z]`/`[^A-Za-z0-9]` counted the `è` of `problème` as a *symbol*,
 * so any accented French word scored two classes and was masked — as was every capitalised word
 * of eight letters (`Dashboard`). A letter is a letter in any script.
 */
export function characterClasses(text: string): number {
  let n = 0
  if (/\p{Ll}/u.test(text)) n++
  if (/\p{Lu}|\p{Lt}/u.test(text)) n++
  if (/\p{N}/u.test(text)) n++
  // Anything that is neither a letter nor a number: punctuation, symbols, marks on their own.
  if (/[^\p{L}\p{N}]/u.test(text)) n++
  return n
}

/**
 * Whether a single token is something the user copied to *go* somewhere rather than to
 * authenticate: a URL or an address. Both mix character classes, and both are copied constantly,
 * so the mixed-class rule below would mask half of a normal clipboard without this.
 *
 * The length rule still applies to them: a URL long enough to be carrying a token is masked.
 */
export function looksLikeDestination(token: string): boolean {
  if (/^[^\s@]+@[^\s@]+\.[A-Za-z]{2,}$/.test(token)) return true
  if (/^(https?|mailto|tel):/i.test(token)) return true
  // A bare host or path, as copied from an address bar without the scheme. Lower case only: a
  // host is written that way, whereas `S3cret.Pass` is shaped like one and is not.
  return /^(www\.|[a-z0-9-]+\.[a-z]{2,24}(\/|$))/.test(token)
}

export interface ClipboardEntry { id: string; text: string; at: number; masked: boolean }
/** What the channel publishes: the preview, never the text. */
export interface PublicEntry { id: string; preview: string; at: number; masked: boolean }
export interface ClipboardSnapshot { entries: PublicEntry[] }

/** Reading and writing the pasteboard, injectable so tests never touch the real one. */
export interface Pasteboard {
  read(): Promise<string>
  write(text: string): Promise<void>
  /**
   * The pasteboard's declared types, so a concealed or transient value can be left alone. A
   * pasteboard that cannot be asked answers an empty list, which records as usual.
   */
  types?(): Promise<string[]>
}

/**
 * The generic pasteboard's type list.
 *
 * A constant script, `-l JavaScript`, no interpolation: nothing from the pasteboard or from a
 * widget reaches `osascript`.
 */
const TYPES_SCRIPT = "ObjC.import('AppKit'); ObjC.deepUnwrap($.NSPasteboard.generalPasteboard.types).join('\\n')"

/** True when the pasteboard asks not to be remembered. */
export function isPrivatePasteboard(types: string[]): boolean {
  return types.some((t) => PRIVATE_PASTEBOARD_TYPES.includes(t.trim()))
}

export const pbPasteboard: Pasteboard = {
  read: () => new Promise((resolve, reject) => {
    execFile('pbpaste', [], { timeout: 5000, maxBuffer: 1024 * 1024 }, (err, stdout) => {
      // A pasteboard holding no text at all is not an error: it is simply nothing to record.
      if (err) reject(new Error(err.message))
      else resolve(stdout)
    })
  }),
  write: (text) => new Promise((resolve, reject) => {
    const child = execFile('pbcopy', [], { timeout: 5000 }, (err) => (err ? reject(new Error(err.message)) : resolve()))
    child.stdin?.end(text)
  }),
  types: () => new Promise((resolve) => {
    execFile('osascript', ['-l', 'JavaScript', '-e', TYPES_SCRIPT], { timeout: 5000 }, (err, stdout) => {
      // A machine that will not run this simply gets the old behaviour, not an empty widget.
      resolve(err ? [] : stdout.split('\n').map((t) => t.trim()).filter(Boolean))
    })
  }),
}

/** Truncates to `MAX_TEXT_BYTES`, on a character boundary. */
export function capText(text: string): string {
  if (Buffer.byteLength(text) <= MAX_TEXT_BYTES) return text
  let cut = text.slice(0, MAX_TEXT_BYTES)
  while (cut.length > 0 && Buffer.byteLength(cut) > MAX_TEXT_BYTES) cut = cut.slice(0, -1)
  return cut
}

/**
 * Whether a text is treated as a secret.
 *
 * Three ways in: it names one outright, it is a long unbroken run (an API key), or it is a
 * shorter unbroken run mixing character classes — which is what an ordinary password looks like,
 * and what the length rule alone used to publish in full onto a screen on a desk.
 *
 * Deliberately generous: a false positive costs the user a preview they can still copy, a false
 * negative puts their password on the wall. Anything with whitespace in it is prose and is left
 * alone unless a marker matches.
 */
export function isSecret(text: string): boolean {
  const trimmed = text.trim()
  const lower = trimmed.toLowerCase()
  if (SECRET_MARKERS.some((marker) => lower.includes(marker))) return true
  if (/\s/.test(trimmed)) return false
  if (trimmed.length >= SECRET_MIN_LENGTH) return true
  if (trimmed.length < SECRET_TOKEN_MIN_LENGTH) return false
  if (looksLikeDestination(trimmed)) return false
  // In the 8–31 band, two classes is what an ordinary capitalised word has. A password has a
  // digit in it, or three classes: `Tr0ub4dor&3`, `hunter2!A`, `aB3dEf9h` — not `Dashboard`.
  const classes = characterClasses(trimmed)
  return classes >= 3 || (classes >= 2 && /\p{N}/u.test(trimmed))
}

export function previewOf(text: string, masked: boolean): string {
  if (masked) return MASKED_PREVIEW
  return text.slice(0, PREVIEW_CHARS)
}

const hash = (text: string): string => createHash('sha256').update(text).digest('hex')

const CopyPayloadSchema = z.object({ id: z.string().min(1).max(64) })

export function createClipboardProvider(pasteboard: Pasteboard = pbPasteboard, now: () => number = Date.now): Provider {
  /** Newest first. */
  let entries: ClipboardEntry[] = []
  const hashes = new Map<string, string>() // hash -> entry id
  let lastHash: string | null = null
  /**
   * The last concealed text seen, kept apart from `lastHash`.
   *
   * A concealed reading is deliberately *not* remembered as seen: copy the same text again from
   * somewhere that does not conceal it and that copy is the user's to keep. But "not seen" also
   * meant "ask again", so `osascript` was forked once a second for the whole time a password sat
   * on the pasteboard — the one case the throttle existed for. Remembered here instead: the same
   * concealed text is not re-queried, and a new one still is.
   */
  let lastConcealedHash: string | null = null
  let nextId = 1

  const publicEntries = (): PublicEntry[] =>
    entries.map((e) => ({ id: e.id, preview: previewOf(e.text, e.masked), at: e.at, masked: e.masked }))

  /** Records a pasteboard reading, moving a text already known back to the front. */
  const record = (raw: string): void => {
    const text = capText(raw)
    if (!text.trim()) return
    const key = hash(text)
    if (key === lastHash) return
    lastHash = key
    const knownId = hashes.get(key)
    if (knownId) {
      const index = entries.findIndex((e) => e.id === knownId)
      if (index >= 0) {
        const [existing] = entries.splice(index, 1)
        existing.at = now()
        entries.unshift(existing)
        return
      }
      hashes.delete(key)
    }
    const entry: ClipboardEntry = { id: String(nextId++), text, at: now(), masked: isSecret(text) }
    entries.unshift(entry)
    hashes.set(key, entry.id)
    for (const dropped of entries.splice(MAX_ENTRIES)) {
      for (const [h, id] of hashes) if (id === dropped.id) hashes.delete(h)
    }
  }

  return {
    channel: 'clipboard',
    intervalMs: 1000,
    async poll(): Promise<ClipboardSnapshot> {
      let raw: string
      try {
        raw = await pasteboard.read()
      } catch {
        // An unreadable pasteboard (no text on it, `pbpaste` unavailable) leaves the history as
        // it is rather than emptying the widget.
        return { entries: publicEntries() }
      }
      const text = capText(raw)
      const key = text.trim() ? hash(text) : null
      // Nothing new on the pasteboard: no need to ask what its types are. That question forks
      // `osascript -l JavaScript` with an AppKit import, which is 100–200 ms of CPU — once a
      // second, for ever, on a dashboard that is always on.
      if (key !== null && key !== lastHash && key !== lastConcealedHash) {
        // Asked before the text is recorded: what a password manager copies is marked concealed,
        // and the point is not to hold it at all, not to hold it masked. A pasteboard that cannot
        // be asked — no `types`, or one that throws — is treated as ordinary, which is the
        // behaviour this had before the question existed.
        const types = await Promise.resolve(pasteboard.types?.() ?? []).catch(() => [])
        if (isPrivatePasteboard(types)) {
          // Not recorded, and not remembered as "seen" either: if the user copies the same text
          // again from somewhere that does not conceal it, that copy is theirs to keep. Only that
          // it was *asked about* is remembered, so the next poll does not fork osascript again.
          lastConcealedHash = key
          return { entries: publicEntries() }
        }
        lastConcealedHash = null
        record(raw)
      }
      return { entries: publicEntries() }
    },
    /** The history never outlives the server, and never outlives the widget that showed it. */
    stop() {
      entries = []
      hashes.clear()
      lastHash = null
      lastConcealedHash = null
    },
    commands: {
      copy: async (payload, ctx?: CommandContext) => {
        // Writing the pasteboard acts on the user's Mac: only a client on that Mac may ask.
        if (!ctx?.loopback) return { ok: false, error: tr(undefined, 'provider.localOnly') }
        const parsed = CopyPayloadSchema.safeParse(payload)
        if (!parsed.success) return { ok: false, error: tr(undefined, 'provider.invalidPayload') }
        const entry = entries.find((e) => e.id === parsed.data.id)
        if (!entry) return { ok: false, error: tr(undefined, 'clipboard.unknownEntry') }
        try {
          await pasteboard.write(entry.text)
        } catch (err) {
          return { ok: false, error: (err as Error).message || String(err) }
        }
        // The next poll would otherwise see this as a fresh copy and reorder the list under the
        // finger that just tapped it.
        lastHash = hash(entry.text)
        return { ok: true }
      },
      clear: async (_payload, ctx?: CommandContext) => {
        // Emptying the history is acting on what the user's Mac has copied, exactly as `copy` is:
        // same gate, for the same reason.
        if (!ctx?.loopback) return { ok: false, error: tr(undefined, 'provider.localOnly') }
        entries = []
        hashes.clear()
        // `lastHash` deliberately survives: it is what keeps the text still sitting on the
        // pasteboard from being recorded straight back a second later, which would make Clear look
        // like it did nothing. Copy anything else and the next copy of that text is recorded
        // again. `lastConcealedHash` is only a throttle, so it goes.
        lastConcealedHash = null
        return { ok: true, entries: [] as PublicEntry[] }
      },
    },
  }
}
